---
title: "wk3_prac_coding"
author: "chris"
date: "2021/12/9"
output: html_document
---

# 3.3.1.1 Vector
```{r}
library(sf)
library(here)
library(raster)
library(tidyverse)
library(rmapshaper)
library(ggplot2)
library(plotly)
```

```{r}
st_layers(here('data',
               'gadm36_CHN_gpkg',
               'gadm36_CHN.gpkg'))

CHNoutline <- st_read(here::here('data',
                                 'gadm36_CHN_gpkg',
                                 'gadm36_CHN.gpkg'),
                                  layer = 'gadm36_CHN_0')
```

```{r}
#使用打印功能检查sf或sp对象的坐标参考系：
print(CHNoutline)
```

```{r}
#3.5.1.2 Prj4
st_crs(CHNoutline)$proj4string
```

```{r}
#3.5.1.3 EPSG
CHNoutline <- CHNoutline %>%
  st_set_crs(.,4326)
```

```{r}
CHNoutline <- st_read(here::here('data',
                                 'gadm36_CHN_gpkg',
                                 'gadm36_CHN.gpkg'),
                                  layer = 'gadm36_CHN_0')%>%
  st_set_crs(4326)
```


```{r}
#3.5.1.4 Reprojecting your spatial data
CHNoutlinePROJECTED <-CHNoutline%>%
  st_transform(.,3415)

print(CHNoutlinePROJECTED)
```

```{r}
#From sf to sp
CHNoutlineSP <- CHNoutline %>%
  as(.,"Spatial")
#From sp to sf
CHNoutlineSF <- CHNoutlineSP %>%
  st_as_sf()
```

#3.5.2 WorldClim data
```{r}
library(raster)
jan <- raster(here::here('data',
                         'wc2.1_5m_tavg',
                         'wc2.1_5m_tavg_01.tif'))
jan
```
```{r}
plot(jan)
```
```{r}
# set the proj 4 to a new object
newproj<-"+proj=moll +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"
# get the jan raster and give it the new proj4
pr1 <- jan %>%
  projectRaster(., crs=newproj)

pr1
```
```{r}
plot(pr1)
```
```{r}
#3.5.3 Data Loading
library(fs)
dir_info("data/wc2.1_5m_tavg/") 
```

```{r}
library(tidyverse)
listfiles <- dir_info("data/wc2.1_5m_tavg")%>%
  filter(str_detect(path,".tif"))%>%
  dplyr::select(path)%>%
  pull()

listfiles
```

```{r}
worldclitemp <-listfiles %>%
  stack()
#have a look at the raster stack
worldclitemp
```

```{r}
# access the january layer
worldclitemp[[1]]
```

```{r}
month <- c("Jan","Feb","Mar","Apr","May","Jun",
           "Jul","Aug","Sep","Oct","Nov","Dec")
names(worldclitemp)<-month
```

```{r}
worldclitemp$Jan
```

```{r}

#3.5.4Raster location
site <- c("Brisbane", "Melbourne", "Perth", "Sydney", "Broome", "Darwin", "Orange", 
          "Bunbury", "Cairns", "Adelaide", "Gold Coast", "Canberra", "Newcastle", 
          "Wollongong", "Logan City" )
lon <- c(153.03, 144.96, 115.86, 151.21, 122.23, 130.84, 149.10, 115.64, 145.77, 
         138.6, 153.43, 149.13, 151.78, 150.89, 153.12)
lat <- c(-27.47, -37.91, -31.95, -33.87, 17.96, -12.46, -33.28, -33.33, -16.92, 
         -34.93, -28, -35.28, -32.93, -34.42, -27.64)
#Put all of this inforamtion into one list 
samples <- data.frame(site, lon, lat, row.names="site")
# Extract the data from the Rasterstack for all points 
AUcitytemp<- raster::extract(worldclitemp, samples)
```

```{r}
#将城市名称添加到 AUcitytemp 的行中
Aucitytemp2 <-AUcitytemp %>%
  as_tibble()%>%
  add_column(site = site,.before ="Jan")
```

# 3.6.1 data preparation 
```{r}
Perthtemp <- Aucitytemp2 %>%
  filter(site=="Perth")
```

# 3.6.2 hisogram
```{r}
hist(as.numeric(Perthtemp))
```

```{r}
#define where you want the breaks in the historgram
userbreak <-c(8,10,12,14,16,18,20,22,24,26)
hist(as.numeric(Perthtemp),
     breaks=userbreak,
     col="red",
     main="Histogram of Perth Temperature",
     xlab="Temperature",
     ylab="Frequency")
```

```{r}
#check out the histogram information R generated
histinfo <- Perthtemp%>%
  as.numeric()%>%
  hist(.)

histinfo
```
# 3.6.3 Using more data
```{r}

plot(CHNoutline$geom)
```

```{r}

#load the rmapshaper package
library(rmapshaper)
library(geojsonsf)
#simplify the shapefile
#keep specifies the % of points
#to keep
CHNoutSIMPLE<-CHNoutline%>%
  ms_simplify(.,keep=0.05)

plot(CHNoutSIMPLE$geom)

```
```{r}

print(CHNoutline)
```

```{r}

#this works nicely for rasters
crs(worldclitemp)
```

```{r}
# now crop our temp data to the extent
CHNtemp<-CHNoutline%>%
  crop(worldclitemp,.)

plot(CHNtemp)
```

```{r}
#subset using the known location of the raster
exactCHN <- CHNtemp %>%
  mask(.,CHNoutline,na.rm=TRUE)

plot(exactCHN)
```
```{r}
#subset using the known location of the raster
hist(exactCHN[[3]],col="red",main="March temperature")
```

```{r}
#OR
#subset with the word Mar
hist(raster::subset(exactCHN, "Mar"), col="red", main ="March temperature")
```
#3.6.4 Histogram with ggplot
```{r}

exactCHNdf <- exactCHN %>%
  as.data.frame()
```

```{r}
library(ggplot2)

gghist <- ggplot(exactCHNdf,
                 aes(x=Mar))+
  geom_histogram(color="black",
                 fill="white")+
  labs(title="Gpplot2 histogram of Australian March temperaures",
       x="Temperature",
       y="Frequency")
#add a vertical line to the hisogram showing mean temperature
gghist +geom_vline(aes(xintercept=mean(Mar,
                                       na.rm=TRUE)),
                   color="blue",
                   linetype="dashed",
                   size=1)+
  theme(plot.title = element_text(hjust = 0.5))
```

```{r}
squishdata <-exactCHNdf%>%
  pivot_longer(
    col=1:12,
    names_to = "Month",
    values_to = "Temp"
  )

squishdata
```


```{r}
twomonths <- squishdata%>%
  #| = or
  filter(.,Month == "Jan" | Month =="Jun")
```

```{r}
meantwomonths <- twomonths %>%
  group_by(Month) %>%
  summarise(mean=mean(Temp, na.rm=TRUE))

meantwomonths
```


```{r}
ggplot(twomonths, aes(x=Temp, color=Month, fill=Month)) +
  geom_histogram(position="identity", alpha=0.5)+
  geom_vline(data=meantwomonths, 
             aes(xintercept=mean, 
                 color=Month),
             linetype="dashed")+
  labs(title="Ggplot2 histogram of China Jan and Jun
       temperatures",
       x="Temperature",
       y="Frequency")+
  theme_classic()+
  theme(plot.title = element_text(hjust = 0.5))
```
```{r}
data_complete_cases <- squishdata %>%
  drop_na()%>% 
  mutate(Month = factor(Month, levels = c("Jan","Feb","Mar",
                                          "Apr","May","Jun",
                                          "Jul","Aug","Sep",
                                          "Oct","Nov","Dec")))
```

```{r}
# Plot faceted histogram
ggplot(data_complete_cases, aes(x=Temp, na.rm=TRUE))+
  geom_histogram(color="black", binwidth = 5)+
  labs(title="Ggplot2 faceted histogram of Australian temperatures", 
       x="Temperature",
       y="Frequency")+
  facet_grid(Month ~ .)+
  theme(plot.title = element_text(hjust = 0.5))
```

```{r}
library(plotly)
# split the data for plotly based on month

jan <- squishdata %>%
  drop_na() %>%
  filter(., Month=="Jan")

jun <- squishdata %>%
  drop_na() %>%
  filter(., Month=="Jun")

# give axis titles
x <- list (title = "Temperature")
y <- list (title = "Frequency")

# set the bin width
xbinsno<-list(start=0, end=40, size = 2.5)

# plot the histogram calling all the variables we just set
ihist<-plot_ly(alpha = 0.6) %>%
  add_histogram(x = jan$Temp,
                xbins=xbinsno, name="January") %>%
  add_histogram(x = jun$Temp,
                xbins=xbinsno, name="June") %>% 
  layout(barmode = "overlay", xaxis=x, yaxis=y)

ihist
```


```{r}
# mean per month
meanofall <- squishdata %>%
  group_by(Month) %>%
  summarise(mean = mean(Temp, na.rm=TRUE))

meanofall
```

```{r}
# standard deviation per month
sdofall <- squishdata %>%
  group_by(Month) %>%
  summarize(sd = sd(Temp, na.rm=TRUE))

sdofall

# maximum per month
maxofall <- squishdata %>%
  group_by(Month) %>%
  summarize(max = max(Temp, na.rm=TRUE))

maxofall

# minimum per month
minofall <- squishdata %>%
  group_by(Month) %>%
  summarize(min = min(Temp, na.rm=TRUE))

minofall

# Interquartlie range per month
IQRofall <- squishdata %>%
  group_by(Month) %>%
  summarize(IQR = IQR(Temp, na.rm=TRUE))

IQRofall

# perhaps you want to store multiple outputs in one list..
lotsofstats <- squishdata %>%
  group_by(Month) %>%
  summarize(IQR = IQR(Temp, na.rm=TRUE), 
            max=max(Temp, na.rm=T))

# or you want to know the mean (or some other stat) 
#for the whole year as opposed to each month...

meanwholeyear=squishdata %>%
  summarize(meanyear = mean(Temp, na.rm=TRUE))

meanwholeyear
```




